const LOGINHANDLER="loginHandler";
const SIGNUPHANDLER= "signUpHandler";
const ADDEXPENSEHANDLER= "addExpenseHandler";
const PASSPORTHANDLER="passportHandler";
const ACCEPTINVITEHANDLER ="acceptInviteHandler";
const CREATEGROUPHANDLER ="createGroupHandler";
const GETALLUSERSHANDLER ="getAllUsersHandler";
const GETGROUPDETAILSHANDLER= "getGroupDetailsHandler";
const GETGROUPINVITESHANDLER= "getGroupInvitesHandler";
const GETGROUPMEMBERSHIPSHANDLER ="getGroupMembershipsHandler";
const REJECTINVITEHANDLER ="rejectInviteHandler";
const USERUPDATEIMAGEHANDLER ="userUpdateImageHandler";
const GROUPUPDATEIMAGEHANDLER ="groupUpdateImageHandler";
const GETPROFILEHANDLER="getProfileHandler";
const UPDATEPROFILEHANDLER="updateProfileHandler";
const LEAVEGROUPHANDLER="leaveGroupHandler";
const RECENTACTIVITYHANDLER="recentactivityHandler";
const ADDCOMMENTHANDLER="addcommenthandler";

module.exports={
    LOGINHANDLER,
    SIGNUPHANDLER,
    ADDEXPENSEHANDLER,
    PASSPORTHANDLER,
    ACCEPTINVITEHANDLER,
    CREATEGROUPHANDLER,
    GETALLUSERSHANDLER,
    GETGROUPDETAILSHANDLER,
    GETGROUPINVITESHANDLER,
    GETGROUPMEMBERSHIPSHANDLER,
    REJECTINVITEHANDLER,
    USERUPDATEIMAGEHANDLER,
    GROUPUPDATEIMAGEHANDLER,
    GETPROFILEHANDLER,
    UPDATEPROFILEHANDLER,
    LEAVEGROUPHANDLER,
    RECENTACTIVITYHANDLER,
    ADDCOMMENTHANDLER
};